import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const db = new PrismaClient({ adapter });

const PRESET_TAGS = [
  "Array", "String", "Hash Table", "Two Pointers", "Sliding Window",
  "Stack", "Queue", "Linked List", "Binary Search", "Tree",
  "Binary Tree", "Binary Search Tree", "Graph", "BFS", "DFS", "Heap",
  "Trie", "Backtracking", "Dynamic Programming", "Greedy", "Sorting",
  "Bit Manipulation", "Math", "Recursion", "Union Find", "Topological Sort",
  "Matrix", "Interval", "Monotonic Stack", "Prefix Sum",
];

type Problem = { t: string; u: string; d: "EASY" | "MEDIUM" | "HARD"; c: string };

const BASE = "https://leetcode.com/problems/";

// 500 problems across 13 topics ordered by prerequisites.
// Within each topic: Easy → Medium → Hard.
const PROBLEMS: Problem[] = [
  // ─── ARRAYS (1-55) ────────────────────────────────────────────────────────
  { t: "Two Sum", u: "two-sum", d: "EASY", c: "arrays" },
  { t: "Best Time to Buy and Sell Stock", u: "best-time-to-buy-and-sell-stock", d: "EASY", c: "arrays" },
  { t: "Contains Duplicate", u: "contains-duplicate", d: "EASY", c: "arrays" },
  { t: "Move Zeroes", u: "move-zeroes", d: "EASY", c: "arrays" },
  { t: "Missing Number", u: "missing-number", d: "EASY", c: "arrays" },
  { t: "Single Number", u: "single-number", d: "EASY", c: "arrays" },
  { t: "Majority Element", u: "majority-element", d: "EASY", c: "arrays" },
  { t: "Plus One", u: "plus-one", d: "EASY", c: "arrays" },
  { t: "Remove Duplicates from Sorted Array", u: "remove-duplicates-from-sorted-array", d: "EASY", c: "arrays" },
  { t: "Squares of a Sorted Array", u: "squares-of-a-sorted-array", d: "EASY", c: "arrays" },
  { t: "Maximum Subarray", u: "maximum-subarray", d: "EASY", c: "arrays" },
  { t: "Running Sum of 1d Array", u: "running-sum-of-1d-array", d: "EASY", c: "arrays" },
  { t: "Binary Search", u: "binary-search", d: "EASY", c: "arrays" },
  { t: "Merge Sorted Array", u: "merge-sorted-array", d: "EASY", c: "arrays" },
  { t: "Max Consecutive Ones", u: "max-consecutive-ones", d: "EASY", c: "arrays" },
  { t: "3Sum", u: "3sum", d: "MEDIUM", c: "arrays" },
  { t: "Container With Most Water", u: "container-with-most-water", d: "MEDIUM", c: "arrays" },
  { t: "Product of Array Except Self", u: "product-of-array-except-self", d: "MEDIUM", c: "arrays" },
  { t: "Maximum Product Subarray", u: "maximum-product-subarray", d: "MEDIUM", c: "arrays" },
  { t: "Find Minimum in Rotated Sorted Array", u: "find-minimum-in-rotated-sorted-array", d: "MEDIUM", c: "arrays" },
  { t: "Search in Rotated Sorted Array", u: "search-in-rotated-sorted-array", d: "MEDIUM", c: "arrays" },
  { t: "Jump Game", u: "jump-game", d: "MEDIUM", c: "arrays" },
  { t: "Jump Game II", u: "jump-game-ii", d: "MEDIUM", c: "arrays" },
  { t: "Merge Intervals", u: "merge-intervals", d: "MEDIUM", c: "arrays" },
  { t: "Insert Interval", u: "insert-interval", d: "MEDIUM", c: "arrays" },
  { t: "Spiral Matrix", u: "spiral-matrix", d: "MEDIUM", c: "arrays" },
  { t: "Rotate Image", u: "rotate-image", d: "MEDIUM", c: "arrays" },
  { t: "Set Matrix Zeroes", u: "set-matrix-zeroes", d: "MEDIUM", c: "arrays" },
  { t: "Next Permutation", u: "next-permutation", d: "MEDIUM", c: "arrays" },
  { t: "Find the Duplicate Number", u: "find-the-duplicate-number", d: "MEDIUM", c: "arrays" },
  { t: "Subarray Sum Equals K", u: "subarray-sum-equals-k", d: "MEDIUM", c: "arrays" },
  { t: "Minimum Size Subarray Sum", u: "minimum-size-subarray-sum", d: "MEDIUM", c: "arrays" },
  { t: "Fruit Into Baskets", u: "fruit-into-baskets", d: "MEDIUM", c: "arrays" },
  { t: "Longest Consecutive Sequence", u: "longest-consecutive-sequence", d: "MEDIUM", c: "arrays" },
  { t: "4Sum", u: "4sum", d: "MEDIUM", c: "arrays" },
  { t: "Sort Colors", u: "sort-colors", d: "MEDIUM", c: "arrays" },
  { t: "Two Sum II - Input Array Is Sorted", u: "two-sum-ii-input-array-is-sorted", d: "MEDIUM", c: "arrays" },
  { t: "Rotate Array", u: "rotate-array", d: "MEDIUM", c: "arrays" },
  { t: "Game of Life", u: "game-of-life", d: "MEDIUM", c: "arrays" },
  { t: "Search a 2D Matrix", u: "search-a-2d-matrix", d: "MEDIUM", c: "arrays" },
  { t: "Find First and Last Position of Element in Sorted Array", u: "find-first-and-last-position-of-element-in-sorted-array", d: "MEDIUM", c: "arrays" },
  { t: "Kth Largest Element in an Array", u: "kth-largest-element-in-an-array", d: "MEDIUM", c: "arrays" },
  { t: "Non-overlapping Intervals", u: "non-overlapping-intervals", d: "MEDIUM", c: "arrays" },
  { t: "Max Consecutive Ones III", u: "max-consecutive-ones-iii", d: "MEDIUM", c: "arrays" },
  { t: "Minimum Operations to Reduce X to Zero", u: "minimum-operations-to-reduce-x-to-zero", d: "MEDIUM", c: "arrays" },
  { t: "Trapping Rain Water", u: "trapping-rain-water", d: "HARD", c: "arrays" },
  { t: "First Missing Positive", u: "first-missing-positive", d: "HARD", c: "arrays" },
  { t: "Median of Two Sorted Arrays", u: "median-of-two-sorted-arrays", d: "HARD", c: "arrays" },
  { t: "Largest Rectangle in Histogram", u: "largest-rectangle-in-histogram", d: "HARD", c: "arrays" },
  { t: "Maximal Rectangle", u: "maximal-rectangle", d: "HARD", c: "arrays" },
  { t: "Best Time to Buy and Sell Stock III", u: "best-time-to-buy-and-sell-stock-iii", d: "HARD", c: "arrays" },
  { t: "Best Time to Buy and Sell Stock IV", u: "best-time-to-buy-and-sell-stock-iv", d: "HARD", c: "arrays" },
  { t: "Count of Smaller Numbers After Self", u: "count-of-smaller-numbers-after-self", d: "HARD", c: "arrays" },
  { t: "Sliding Window Maximum", u: "sliding-window-maximum", d: "HARD", c: "arrays" },
  { t: "Reverse Pairs", u: "reverse-pairs", d: "HARD", c: "arrays" },

  // ─── HASHING (56-80) ──────────────────────────────────────────────────────
  { t: "Valid Anagram", u: "valid-anagram", d: "EASY", c: "hashing" },
  { t: "Ransom Note", u: "ransom-note", d: "EASY", c: "hashing" },
  { t: "Word Pattern", u: "word-pattern", d: "EASY", c: "hashing" },
  { t: "Isomorphic Strings", u: "isomorphic-strings", d: "EASY", c: "hashing" },
  { t: "Contains Duplicate II", u: "contains-duplicate-ii", d: "EASY", c: "hashing" },
  { t: "Intersection of Two Arrays", u: "intersection-of-two-arrays", d: "EASY", c: "hashing" },
  { t: "Happy Number", u: "happy-number", d: "EASY", c: "hashing" },
  { t: "Group Anagrams", u: "group-anagrams", d: "MEDIUM", c: "hashing" },
  { t: "Top K Frequent Elements", u: "top-k-frequent-elements", d: "MEDIUM", c: "hashing" },
  { t: "4Sum II", u: "4sum-ii", d: "MEDIUM", c: "hashing" },
  { t: "Contiguous Array", u: "contiguous-array", d: "MEDIUM", c: "hashing" },
  { t: "Sort Characters By Frequency", u: "sort-characters-by-frequency", d: "MEDIUM", c: "hashing" },
  { t: "Insert Delete GetRandom O(1)", u: "insert-delete-getrandom-o1", d: "MEDIUM", c: "hashing" },
  { t: "Repeated DNA Sequences", u: "repeated-dna-sequences", d: "MEDIUM", c: "hashing" },
  { t: "Brick Wall", u: "brick-wall", d: "MEDIUM", c: "hashing" },
  { t: "Pairs of Songs With Total Durations Divisible by 60", u: "pairs-of-songs-with-total-durations-divisible-by-60", d: "MEDIUM", c: "hashing" },
  { t: "Frequency of the Most Frequent Element", u: "frequency-of-the-most-frequent-element", d: "MEDIUM", c: "hashing" },
  { t: "Equal Row and Column Pairs", u: "equal-row-and-column-pairs", d: "MEDIUM", c: "hashing" },
  { t: "Subarray Sums Divisible by K", u: "subarray-sums-divisible-by-k", d: "MEDIUM", c: "hashing" },
  { t: "Count Number of Nice Subarrays", u: "count-number-of-nice-subarrays", d: "MEDIUM", c: "hashing" },
  { t: "Unique Number of Occurrences", u: "unique-number-of-occurrences", d: "EASY", c: "hashing" },
  { t: "Number of Good Pairs", u: "number-of-good-pairs", d: "EASY", c: "hashing" },
  { t: "Minimum Window Substring", u: "minimum-window-substring", d: "HARD", c: "hashing" },
  { t: "Subarrays with K Different Integers", u: "subarrays-with-k-different-integers", d: "HARD", c: "hashing" },
  { t: "Max Points on a Line", u: "max-points-on-a-line", d: "HARD", c: "hashing" },

  // ─── STRING (81-125) ──────────────────────────────────────────────────────
  { t: "Valid Palindrome", u: "valid-palindrome", d: "EASY", c: "string" },
  { t: "Reverse String", u: "reverse-string", d: "EASY", c: "string" },
  { t: "First Unique Character in a String", u: "first-unique-character-in-a-string", d: "EASY", c: "string" },
  { t: "Longest Common Prefix", u: "longest-common-prefix", d: "EASY", c: "string" },
  { t: "Roman to Integer", u: "roman-to-integer", d: "EASY", c: "string" },
  { t: "Detect Capital", u: "detect-capital", d: "EASY", c: "string" },
  { t: "Reverse Words in a String III", u: "reverse-words-in-a-string-iii", d: "EASY", c: "string" },
  { t: "To Lower Case", u: "to-lower-case", d: "EASY", c: "string" },
  { t: "Implement strStr()", u: "find-the-index-of-the-first-occurrence-in-a-string", d: "EASY", c: "string" },
  { t: "Add Strings", u: "add-strings", d: "EASY", c: "string" },
  { t: "Longest Substring Without Repeating Characters", u: "longest-substring-without-repeating-characters", d: "MEDIUM", c: "string" },
  { t: "Longest Palindromic Substring", u: "longest-palindromic-substring", d: "MEDIUM", c: "string" },
  { t: "String to Integer (atoi)", u: "string-to-integer-atoi", d: "MEDIUM", c: "string" },
  { t: "Zigzag Conversion", u: "zigzag-conversion", d: "MEDIUM", c: "string" },
  { t: "Reverse Words in a String", u: "reverse-words-in-a-string", d: "MEDIUM", c: "string" },
  { t: "Palindromic Substrings", u: "palindromic-substrings", d: "MEDIUM", c: "string" },
  { t: "Longest Repeating Character Replacement", u: "longest-repeating-character-replacement", d: "MEDIUM", c: "string" },
  { t: "Permutation in String", u: "permutation-in-string", d: "MEDIUM", c: "string" },
  { t: "Find All Anagrams in a String", u: "find-all-anagrams-in-a-string", d: "MEDIUM", c: "string" },
  { t: "Count and Say", u: "count-and-say", d: "MEDIUM", c: "string" },
  { t: "Decode Ways", u: "decode-ways", d: "MEDIUM", c: "string" },
  { t: "Compare Version Numbers", u: "compare-version-numbers", d: "MEDIUM", c: "string" },
  { t: "Integer to Roman", u: "integer-to-roman", d: "MEDIUM", c: "string" },
  { t: "Multiply Strings", u: "multiply-strings", d: "MEDIUM", c: "string" },
  { t: "Simplify Path", u: "simplify-path", d: "MEDIUM", c: "string" },
  { t: "Word Break", u: "word-break", d: "MEDIUM", c: "string" },
  { t: "Minimum Remove to Make Valid Parentheses", u: "minimum-remove-to-make-valid-parentheses", d: "MEDIUM", c: "string" },
  { t: "String Compression", u: "string-compression", d: "MEDIUM", c: "string" },
  { t: "Reorganize String", u: "reorganize-string", d: "MEDIUM", c: "string" },
  { t: "Partition Labels", u: "partition-labels", d: "MEDIUM", c: "string" },
  { t: "Decode String", u: "decode-string", d: "MEDIUM", c: "string" },
  { t: "Basic Calculator II", u: "basic-calculator-ii", d: "MEDIUM", c: "string" },
  { t: "Encode and Decode Strings", u: "encode-and-decode-strings", d: "MEDIUM", c: "string" },
  { t: "Restore IP Addresses", u: "restore-ip-addresses", d: "MEDIUM", c: "string" },
  { t: "Remove Duplicate Letters", u: "remove-duplicate-letters", d: "MEDIUM", c: "string" },
  { t: "Wildcard Matching", u: "wildcard-matching", d: "HARD", c: "string" },
  { t: "Regular Expression Matching", u: "regular-expression-matching", d: "HARD", c: "string" },
  { t: "Text Justification", u: "text-justification", d: "HARD", c: "string" },
  { t: "Word Ladder", u: "word-ladder", d: "HARD", c: "string" },
  { t: "Longest Valid Parentheses", u: "longest-valid-parentheses", d: "HARD", c: "string" },
  { t: "Basic Calculator", u: "basic-calculator", d: "HARD", c: "string" },
  { t: "Distinct Subsequences", u: "distinct-subsequences", d: "HARD", c: "string" },
  { t: "Palindrome Pairs", u: "palindrome-pairs", d: "HARD", c: "string" },
  { t: "Scramble String", u: "scramble-string", d: "HARD", c: "string" },
  { t: "Minimum Window Subsequence", u: "minimum-window-subsequence", d: "HARD", c: "string" },

  // ─── SORTING (126-145) ────────────────────────────────────────────────────
  { t: "Sort Array by Parity", u: "sort-array-by-parity", d: "EASY", c: "sorting" },
  { t: "Sort Array By Parity II", u: "sort-array-by-parity-ii", d: "EASY", c: "sorting" },
  { t: "Sort the People", u: "sort-the-people", d: "EASY", c: "sorting" },
  { t: "Array Partition", u: "array-partition", d: "EASY", c: "sorting" },
  { t: "Sort an Array", u: "sort-an-array", d: "MEDIUM", c: "sorting" },
  { t: "Largest Number", u: "largest-number", d: "MEDIUM", c: "sorting" },
  { t: "Sort List", u: "sort-list", d: "MEDIUM", c: "sorting" },
  { t: "Custom Sort String", u: "custom-sort-string", d: "MEDIUM", c: "sorting" },
  { t: "H-Index", u: "h-index", d: "MEDIUM", c: "sorting" },
  { t: "Minimum Number of Arrows to Burst Balloons", u: "minimum-number-of-arrows-to-burst-balloons", d: "MEDIUM", c: "sorting" },
  { t: "Car Fleet", u: "car-fleet", d: "MEDIUM", c: "sorting" },
  { t: "K Closest Points to Origin", u: "k-closest-points-to-origin", d: "MEDIUM", c: "sorting" },
  { t: "Queue Reconstruction by Height", u: "queue-reconstruction-by-height", d: "MEDIUM", c: "sorting" },
  { t: "Pancake Sorting", u: "pancake-sorting", d: "MEDIUM", c: "sorting" },
  { t: "Sort Integers by The Number of 1 Bits", u: "sort-integers-by-the-number-of-1-bits", d: "EASY", c: "sorting" },
  { t: "Wiggle Sort II", u: "wiggle-sort-ii", d: "MEDIUM", c: "sorting" },
  { t: "Relative Sort Array", u: "relative-sort-array", d: "EASY", c: "sorting" },
  { t: "Maximum Gap", u: "maximum-gap", d: "HARD", c: "sorting" },
  { t: "Minimum Cost to Hire K Workers", u: "minimum-cost-to-hire-k-workers", d: "HARD", c: "sorting" },
  { t: "Count of Range Sum", u: "count-of-range-sum", d: "HARD", c: "sorting" },

  // ─── LINKED LIST (146-180) ────────────────────────────────────────────────
  { t: "Reverse Linked List", u: "reverse-linked-list", d: "EASY", c: "linked list" },
  { t: "Merge Two Sorted Lists", u: "merge-two-sorted-lists", d: "EASY", c: "linked list" },
  { t: "Linked List Cycle", u: "linked-list-cycle", d: "EASY", c: "linked list" },
  { t: "Palindrome Linked List", u: "palindrome-linked-list", d: "EASY", c: "linked list" },
  { t: "Remove Linked List Elements", u: "remove-linked-list-elements", d: "EASY", c: "linked list" },
  { t: "Middle of the Linked List", u: "middle-of-the-linked-list", d: "EASY", c: "linked list" },
  { t: "Intersection of Two Linked Lists", u: "intersection-of-two-linked-lists", d: "EASY", c: "linked list" },
  { t: "Delete Node in a Linked List", u: "delete-node-in-a-linked-list", d: "MEDIUM", c: "linked list" },
  { t: "Remove Duplicates from Sorted List", u: "remove-duplicates-from-sorted-list", d: "EASY", c: "linked list" },
  { t: "Reorder List", u: "reorder-list", d: "MEDIUM", c: "linked list" },
  { t: "Remove Nth Node From End of List", u: "remove-nth-node-from-end-of-list", d: "MEDIUM", c: "linked list" },
  { t: "Linked List Cycle II", u: "linked-list-cycle-ii", d: "MEDIUM", c: "linked list" },
  { t: "Add Two Numbers", u: "add-two-numbers", d: "MEDIUM", c: "linked list" },
  { t: "Rotate List", u: "rotate-list", d: "MEDIUM", c: "linked list" },
  { t: "Odd Even Linked List", u: "odd-even-linked-list", d: "MEDIUM", c: "linked list" },
  { t: "Partition List", u: "partition-list", d: "MEDIUM", c: "linked list" },
  { t: "Swap Nodes in Pairs", u: "swap-nodes-in-pairs", d: "MEDIUM", c: "linked list" },
  { t: "Remove Duplicates from Sorted List II", u: "remove-duplicates-from-sorted-list-ii", d: "MEDIUM", c: "linked list" },
  { t: "Copy List with Random Pointer", u: "copy-list-with-random-pointer", d: "MEDIUM", c: "linked list" },
  { t: "LRU Cache", u: "lru-cache", d: "MEDIUM", c: "linked list" },
  { t: "Next Greater Node In Linked List", u: "next-greater-node-in-linked-list", d: "MEDIUM", c: "linked list" },
  { t: "Reverse Linked List II", u: "reverse-linked-list-ii", d: "MEDIUM", c: "linked list" },
  { t: "Add Two Numbers II", u: "add-two-numbers-ii", d: "MEDIUM", c: "linked list" },
  { t: "Maximum Twin Sum of a Linked List", u: "maximum-twin-sum-of-a-linked-list", d: "MEDIUM", c: "linked list" },
  { t: "Split Linked List in Parts", u: "split-linked-list-in-parts", d: "MEDIUM", c: "linked list" },
  { t: "Design Linked List", u: "design-linked-list", d: "MEDIUM", c: "linked list" },
  { t: "Delete the Middle Node of a Linked List", u: "delete-the-middle-node-of-a-linked-list", d: "MEDIUM", c: "linked list" },
  { t: "Swapping Nodes in a Linked List", u: "swapping-nodes-in-a-linked-list", d: "MEDIUM", c: "linked list" },
  { t: "Reverse Nodes in k-Group", u: "reverse-nodes-in-k-group", d: "HARD", c: "linked list" },
  { t: "Merge k Sorted Lists", u: "merge-k-sorted-lists", d: "HARD", c: "linked list" },
  { t: "LFU Cache", u: "lfu-cache", d: "HARD", c: "linked list" },
  { t: "All O`one Data Structure", u: "all-oone-data-structure", d: "HARD", c: "linked list" },
  { t: "Design Skiplist", u: "design-skiplist", d: "HARD", c: "linked list" },
  { t: "Flatten a Multilevel Doubly Linked List", u: "flatten-a-multilevel-doubly-linked-list", d: "MEDIUM", c: "linked list" },
  { t: "Double a Number Represented as a Linked List", u: "double-a-number-represented-as-a-linked-list", d: "MEDIUM", c: "linked list" },

  // ─── STACK (181-210) ──────────────────────────────────────────────────────
  { t: "Valid Parentheses", u: "valid-parentheses", d: "EASY", c: "stack" },
  { t: "Baseball Game", u: "baseball-game", d: "EASY", c: "stack" },
  { t: "Remove Outermost Parentheses", u: "remove-outermost-parentheses", d: "EASY", c: "stack" },
  { t: "Next Greater Element I", u: "next-greater-element-i", d: "EASY", c: "stack" },
  { t: "Backspace String Compare", u: "backspace-string-compare", d: "EASY", c: "stack" },
  { t: "Min Stack", u: "min-stack", d: "MEDIUM", c: "stack" },
  { t: "Daily Temperatures", u: "daily-temperatures", d: "MEDIUM", c: "stack" },
  { t: "Asteroid Collision", u: "asteroid-collision", d: "MEDIUM", c: "stack" },
  { t: "Evaluate Reverse Polish Notation", u: "evaluate-reverse-polish-notation", d: "MEDIUM", c: "stack" },
  { t: "Next Greater Element II", u: "next-greater-element-ii", d: "MEDIUM", c: "stack" },
  { t: "Flatten Nested List Iterator", u: "flatten-nested-list-iterator", d: "MEDIUM", c: "stack" },
  { t: "Exclusive Time of Functions", u: "exclusive-time-of-functions", d: "MEDIUM", c: "stack" },
  { t: "Online Stock Span", u: "online-stock-span", d: "MEDIUM", c: "stack" },
  { t: "132 Pattern", u: "132-pattern", d: "MEDIUM", c: "stack" },
  { t: "Minimum Add to Make Parentheses Valid", u: "minimum-add-to-make-parentheses-valid", d: "MEDIUM", c: "stack" },
  { t: "Score of Parentheses", u: "score-of-parentheses", d: "MEDIUM", c: "stack" },
  { t: "Maximum Width Ramp", u: "maximum-width-ramp", d: "MEDIUM", c: "stack" },
  { t: "Sum of Subarray Minimums", u: "sum-of-subarray-minimums", d: "MEDIUM", c: "stack" },
  { t: "Remove K Digits", u: "remove-k-digits", d: "MEDIUM", c: "stack" },
  { t: "Validate Stack Sequences", u: "validate-stack-sequences", d: "MEDIUM", c: "stack" },
  { t: "Decoded String at Index", u: "decoded-string-at-index", d: "MEDIUM", c: "stack" },
  { t: "Removing Stars From a String", u: "removing-stars-from-a-string", d: "MEDIUM", c: "stack" },
  { t: "Monotone Increasing Digits", u: "monotone-increasing-digits", d: "MEDIUM", c: "stack" },
  { t: "Sum of Subarray Ranges", u: "sum-of-subarray-ranges", d: "MEDIUM", c: "stack" },
  { t: "Minimum Cost Tree From Leaf Values", u: "minimum-cost-tree-from-leaf-values", d: "MEDIUM", c: "stack" },
  { t: "Basic Calculator", u: "basic-calculator", d: "HARD", c: "stack" },
  { t: "Maximum Score of a Good Subarray", u: "maximum-score-of-a-good-subarray", d: "HARD", c: "stack" },
  { t: "Maximum Frequency Stack", u: "maximum-frequency-stack", d: "HARD", c: "stack" },
  { t: "Number of Visible People in a Queue", u: "number-of-visible-people-in-a-queue", d: "HARD", c: "stack" },
  { t: "Longest Valid Parentheses (Stack)", u: "longest-valid-parentheses", d: "HARD", c: "stack" },

  // ─── QUEUE (211-230) ──────────────────────────────────────────────────────
  { t: "Number of Recent Calls", u: "number-of-recent-calls", d: "EASY", c: "queue" },
  { t: "Design Circular Queue", u: "design-circular-queue", d: "MEDIUM", c: "queue" },
  { t: "Task Scheduler", u: "task-scheduler", d: "MEDIUM", c: "queue" },
  { t: "Find Median from Data Stream", u: "find-median-from-data-stream", d: "HARD", c: "queue" },
  { t: "Top K Frequent Words", u: "top-k-frequent-words", d: "MEDIUM", c: "queue" },
  { t: "Reorganize String (Heap)", u: "reorganize-string", d: "MEDIUM", c: "queue" },
  { t: "Kth Largest Element in a Stream", u: "kth-largest-element-in-a-stream", d: "EASY", c: "queue" },
  { t: "K Closest Points to Origin (Heap)", u: "k-closest-points-to-origin", d: "MEDIUM", c: "queue" },
  { t: "Process Tasks Using Servers", u: "process-tasks-using-servers", d: "MEDIUM", c: "queue" },
  { t: "Minimum Cost to Connect Sticks", u: "minimum-cost-to-connect-sticks", d: "MEDIUM", c: "queue" },
  { t: "Furthest Building You Can Reach", u: "furthest-building-you-can-reach", d: "MEDIUM", c: "queue" },
  { t: "Last Stone Weight", u: "last-stone-weight", d: "EASY", c: "queue" },
  { t: "IPO", u: "ipo", d: "HARD", c: "queue" },
  { t: "Minimum Number of Refueling Stops", u: "minimum-number-of-refueling-stops", d: "HARD", c: "queue" },
  { t: "Merge k Sorted Lists (Heap)", u: "merge-k-sorted-lists", d: "HARD", c: "queue" },
  { t: "Ugly Number II", u: "ugly-number-ii", d: "MEDIUM", c: "queue" },
  { t: "Super Ugly Number", u: "super-ugly-number", d: "MEDIUM", c: "queue" },
  { t: "Seat Reservation Manager", u: "seat-reservation-manager", d: "MEDIUM", c: "queue" },
  { t: "Smallest Number in Infinite Set", u: "smallest-number-in-infinite-set", d: "MEDIUM", c: "queue" },
  { t: "Single-Threaded CPU", u: "single-threaded-cpu", d: "MEDIUM", c: "queue" },

  // ─── RECURSION (231-250) ──────────────────────────────────────────────────
  { t: "Power of Two", u: "power-of-two", d: "EASY", c: "recursion" },
  { t: "Reverse Linked List (Recursive)", u: "reverse-linked-list", d: "EASY", c: "recursion" },
  { t: "Fibonacci Number", u: "fibonacci-number", d: "EASY", c: "recursion" },
  { t: "Climbing Stairs", u: "climbing-stairs", d: "EASY", c: "recursion" },
  { t: "Merge Two Sorted Lists (Recursive)", u: "merge-two-sorted-lists", d: "EASY", c: "recursion" },
  { t: "Pow(x, n)", u: "powx-n", d: "MEDIUM", c: "recursion" },
  { t: "Merge Sort (Sort an Array)", u: "sort-an-array", d: "MEDIUM", c: "recursion" },
  { t: "Flatten Nested List Iterator (Recursive)", u: "flatten-nested-list-iterator", d: "MEDIUM", c: "recursion" },
  { t: "K-th Symbol in Grammar", u: "k-th-symbol-in-grammar", d: "MEDIUM", c: "recursion" },
  { t: "Find All Numbers Disappeared in an Array", u: "find-all-numbers-disappeared-in-an-array", d: "EASY", c: "recursion" },
  { t: "Divide Two Integers", u: "divide-two-integers", d: "MEDIUM", c: "recursion" },
  { t: "Count Good Numbers", u: "count-good-numbers", d: "MEDIUM", c: "recursion" },
  { t: "Largest Rectangle in Histogram (D&C)", u: "largest-rectangle-in-histogram", d: "HARD", c: "recursion" },
  { t: "Beautiful Array", u: "beautiful-array", d: "MEDIUM", c: "recursion" },
  { t: "Different Ways to Add Parentheses", u: "different-ways-to-add-parentheses", d: "MEDIUM", c: "recursion" },
  { t: "Super Pow", u: "super-pow", d: "MEDIUM", c: "recursion" },
  { t: "Count of Range Sum (D&C)", u: "count-of-range-sum", d: "HARD", c: "recursion" },
  { t: "Expression Add Operators", u: "expression-add-operators", d: "HARD", c: "recursion" },
  { t: "Construct Quad Tree", u: "construct-quad-tree", d: "MEDIUM", c: "recursion" },
  { t: "Find Kth Bit in Nth Binary String", u: "find-kth-bit-in-nth-binary-string", d: "MEDIUM", c: "recursion" },

  // ─── TREES (251-305) ──────────────────────────────────────────────────────
  { t: "Maximum Depth of Binary Tree", u: "maximum-depth-of-binary-tree", d: "EASY", c: "trees" },
  { t: "Symmetric Tree", u: "symmetric-tree", d: "EASY", c: "trees" },
  { t: "Invert Binary Tree", u: "invert-binary-tree", d: "EASY", c: "trees" },
  { t: "Path Sum", u: "path-sum", d: "EASY", c: "trees" },
  { t: "Merge Two Binary Trees", u: "merge-two-binary-trees", d: "EASY", c: "trees" },
  { t: "Subtree of Another Tree", u: "subtree-of-another-tree", d: "EASY", c: "trees" },
  { t: "Diameter of Binary Tree", u: "diameter-of-binary-tree", d: "EASY", c: "trees" },
  { t: "Same Tree", u: "same-tree", d: "EASY", c: "trees" },
  { t: "Convert Sorted Array to Binary Search Tree", u: "convert-sorted-array-to-binary-search-tree", d: "EASY", c: "trees" },
  { t: "Balanced Binary Tree", u: "balanced-binary-tree", d: "EASY", c: "trees" },
  { t: "Minimum Depth of Binary Tree", u: "minimum-depth-of-binary-tree", d: "EASY", c: "trees" },
  { t: "Binary Tree Level Order Traversal", u: "binary-tree-level-order-traversal", d: "MEDIUM", c: "trees" },
  { t: "Binary Tree Zigzag Level Order Traversal", u: "binary-tree-zigzag-level-order-traversal", d: "MEDIUM", c: "trees" },
  { t: "Binary Tree Right Side View", u: "binary-tree-right-side-view", d: "MEDIUM", c: "trees" },
  { t: "Validate Binary Search Tree", u: "validate-binary-search-tree", d: "MEDIUM", c: "trees" },
  { t: "Lowest Common Ancestor of a BST", u: "lowest-common-ancestor-of-a-binary-search-tree", d: "MEDIUM", c: "trees" },
  { t: "Lowest Common Ancestor of a Binary Tree", u: "lowest-common-ancestor-of-a-binary-tree", d: "MEDIUM", c: "trees" },
  { t: "Binary Search Tree Iterator", u: "binary-search-tree-iterator", d: "MEDIUM", c: "trees" },
  { t: "Kth Smallest Element in a BST", u: "kth-smallest-element-in-a-bst", d: "MEDIUM", c: "trees" },
  { t: "Flatten Binary Tree to Linked List", u: "flatten-binary-tree-to-linked-list", d: "MEDIUM", c: "trees" },
  { t: "Sum Root to Leaf Numbers", u: "sum-root-to-leaf-numbers", d: "MEDIUM", c: "trees" },
  { t: "Path Sum II", u: "path-sum-ii", d: "MEDIUM", c: "trees" },
  { t: "Construct Binary Tree from Preorder and Inorder Traversal", u: "construct-binary-tree-from-preorder-and-inorder-traversal", d: "MEDIUM", c: "trees" },
  { t: "Construct Binary Tree from Inorder and Postorder Traversal", u: "construct-binary-tree-from-inorder-and-postorder-traversal", d: "MEDIUM", c: "trees" },
  { t: "Populating Next Right Pointers in Each Node", u: "populating-next-right-pointers-in-each-node", d: "MEDIUM", c: "trees" },
  { t: "Count Good Nodes in Binary Tree", u: "count-good-nodes-in-binary-tree", d: "MEDIUM", c: "trees" },
  { t: "Serialize and Deserialize BST", u: "serialize-and-deserialize-bst", d: "MEDIUM", c: "trees" },
  { t: "Delete Node in a BST", u: "delete-node-in-a-bst", d: "MEDIUM", c: "trees" },
  { t: "Insert into a Binary Search Tree", u: "insert-into-a-binary-search-tree", d: "MEDIUM", c: "trees" },
  { t: "Maximum Binary Tree", u: "maximum-binary-tree", d: "MEDIUM", c: "trees" },
  { t: "Implement Trie (Prefix Tree)", u: "implement-trie-prefix-tree", d: "MEDIUM", c: "trees" },
  { t: "Add and Search Word", u: "design-add-and-search-words-data-structure", d: "MEDIUM", c: "trees" },
  { t: "House Robber III", u: "house-robber-iii", d: "MEDIUM", c: "trees" },
  { t: "Maximum Width of Binary Tree", u: "maximum-width-of-binary-tree", d: "MEDIUM", c: "trees" },
  { t: "Path Sum III", u: "path-sum-iii", d: "MEDIUM", c: "trees" },
  { t: "All Paths From Source to Target", u: "all-paths-from-source-to-target", d: "MEDIUM", c: "trees" },
  { t: "Unique Binary Search Trees", u: "unique-binary-search-trees", d: "MEDIUM", c: "trees" },
  { t: "Unique Binary Search Trees II", u: "unique-binary-search-trees-ii", d: "MEDIUM", c: "trees" },
  { t: "Binary Tree Maximum Path Sum", u: "binary-tree-maximum-path-sum", d: "HARD", c: "trees" },
  { t: "Serialize and Deserialize Binary Tree", u: "serialize-and-deserialize-binary-tree", d: "HARD", c: "trees" },
  { t: "Binary Tree Cameras", u: "binary-tree-cameras", d: "HARD", c: "trees" },
  { t: "Count Complete Tree Nodes", u: "count-complete-tree-nodes", d: "EASY", c: "trees" },
  { t: "Maximum Level Sum of a Binary Tree", u: "maximum-level-sum-of-a-binary-tree", d: "MEDIUM", c: "trees" },
  { t: "Recover Binary Search Tree", u: "recover-binary-search-tree", d: "MEDIUM", c: "trees" },
  { t: "Word Search II (Trie)", u: "word-search-ii", d: "HARD", c: "trees" },

  // ─── TRAVERSAL (306-335) ──────────────────────────────────────────────────
  { t: "Binary Tree Inorder Traversal", u: "binary-tree-inorder-traversal", d: "EASY", c: "traversal" },
  { t: "Binary Tree Preorder Traversal", u: "binary-tree-preorder-traversal", d: "EASY", c: "traversal" },
  { t: "Binary Tree Postorder Traversal", u: "binary-tree-postorder-traversal", d: "EASY", c: "traversal" },
  { t: "Average of Levels in Binary Tree", u: "average-of-levels-in-binary-tree", d: "EASY", c: "traversal" },
  { t: "Flood Fill", u: "flood-fill", d: "EASY", c: "traversal" },
  { t: "Number of Islands", u: "number-of-islands", d: "MEDIUM", c: "traversal" },
  { t: "Max Area of Island", u: "max-area-of-island", d: "MEDIUM", c: "traversal" },
  { t: "Clone Graph", u: "clone-graph", d: "MEDIUM", c: "traversal" },
  { t: "Pacific Atlantic Water Flow", u: "pacific-atlantic-water-flow", d: "MEDIUM", c: "traversal" },
  { t: "Surrounded Regions", u: "surrounded-regions", d: "MEDIUM", c: "traversal" },
  { t: "Rotting Oranges", u: "rotting-oranges", d: "MEDIUM", c: "traversal" },
  { t: "Word Search", u: "word-search", d: "MEDIUM", c: "traversal" },
  { t: "01 Matrix", u: "01-matrix", d: "MEDIUM", c: "traversal" },
  { t: "Snakes and Ladders", u: "snakes-and-ladders", d: "MEDIUM", c: "traversal" },
  { t: "Open the Lock", u: "open-the-lock", d: "MEDIUM", c: "traversal" },
  { t: "Minimum Knight Moves", u: "minimum-knight-moves", d: "MEDIUM", c: "traversal" },
  { t: "As Far from Land as Possible", u: "as-far-from-land-as-possible", d: "MEDIUM", c: "traversal" },
  { t: "Binary Tree Level Order Traversal II", u: "binary-tree-level-order-traversal-ii", d: "MEDIUM", c: "traversal" },
  { t: "Find Largest Value in Each Tree Row", u: "find-largest-value-in-each-tree-row", d: "MEDIUM", c: "traversal" },
  { t: "Walls and Gates", u: "walls-and-gates", d: "MEDIUM", c: "traversal" },
  { t: "Jump Game III", u: "jump-game-iii", d: "MEDIUM", c: "traversal" },
  { t: "Time Needed to Inform All Employees", u: "time-needed-to-inform-all-employees", d: "MEDIUM", c: "traversal" },
  { t: "Nearest Exit from Entrance in Maze", u: "nearest-exit-from-entrance-in-maze", d: "MEDIUM", c: "traversal" },
  { t: "Minimum Genetic Mutation", u: "minimum-genetic-mutation", d: "MEDIUM", c: "traversal" },
  { t: "Word Ladder II", u: "word-ladder-ii", d: "HARD", c: "traversal" },
  { t: "Bus Routes", u: "bus-routes", d: "HARD", c: "traversal" },
  { t: "Shortest Path in a Grid with Obstacles Elimination", u: "shortest-path-in-a-grid-with-obstacles-elimination", d: "HARD", c: "traversal" },
  { t: "Cut Off Trees for Golf Event", u: "cut-off-trees-for-golf-event", d: "HARD", c: "traversal" },
  { t: "Serialize and Deserialize N-ary Tree", u: "serialize-and-deserialize-n-ary-tree", d: "HARD", c: "traversal" },
  { t: "Binary Tree Vertical Order Traversal", u: "binary-tree-vertical-order-traversal", d: "MEDIUM", c: "traversal" },

  // ─── BACKTRACKING (336-365) ───────────────────────────────────────────────
  { t: "Subsets", u: "subsets", d: "MEDIUM", c: "backtracking" },
  { t: "Permutations", u: "permutations", d: "MEDIUM", c: "backtracking" },
  { t: "Combinations", u: "combinations", d: "MEDIUM", c: "backtracking" },
  { t: "Generate Parentheses", u: "generate-parentheses", d: "MEDIUM", c: "backtracking" },
  { t: "Letter Combinations of a Phone Number", u: "letter-combinations-of-a-phone-number", d: "MEDIUM", c: "backtracking" },
  { t: "Combination Sum", u: "combination-sum", d: "MEDIUM", c: "backtracking" },
  { t: "Combination Sum II", u: "combination-sum-ii", d: "MEDIUM", c: "backtracking" },
  { t: "Subsets II", u: "subsets-ii", d: "MEDIUM", c: "backtracking" },
  { t: "Permutations II", u: "permutations-ii", d: "MEDIUM", c: "backtracking" },
  { t: "Palindrome Partitioning", u: "palindrome-partitioning", d: "MEDIUM", c: "backtracking" },
  { t: "Word Search (Backtracking)", u: "word-search", d: "MEDIUM", c: "backtracking" },
  { t: "Combination Sum III", u: "combination-sum-iii", d: "MEDIUM", c: "backtracking" },
  { t: "Letter Case Permutation", u: "letter-case-permutation", d: "MEDIUM", c: "backtracking" },
  { t: "Path With Maximum Gold", u: "path-with-maximum-gold", d: "MEDIUM", c: "backtracking" },
  { t: "Restore IP Addresses (Backtracking)", u: "restore-ip-addresses", d: "MEDIUM", c: "backtracking" },
  { t: "Gray Code", u: "gray-code", d: "MEDIUM", c: "backtracking" },
  { t: "Beautiful Arrangement", u: "beautiful-arrangement", d: "MEDIUM", c: "backtracking" },
  { t: "All Paths From Source to Target (Backtracking)", u: "all-paths-from-source-to-target", d: "MEDIUM", c: "backtracking" },
  { t: "Count Numbers with Unique Digits", u: "count-numbers-with-unique-digits", d: "MEDIUM", c: "backtracking" },
  { t: "Factor Combinations", u: "factor-combinations", d: "MEDIUM", c: "backtracking" },
  { t: "N-Queens", u: "n-queens", d: "HARD", c: "backtracking" },
  { t: "N-Queens II", u: "n-queens-ii", d: "HARD", c: "backtracking" },
  { t: "Sudoku Solver", u: "sudoku-solver", d: "HARD", c: "backtracking" },
  { t: "Regular Expression Matching (Backtracking)", u: "regular-expression-matching", d: "HARD", c: "backtracking" },
  { t: "Remove Invalid Parentheses", u: "remove-invalid-parentheses", d: "HARD", c: "backtracking" },
  { t: "Word Break II", u: "word-break-ii", d: "HARD", c: "backtracking" },
  { t: "Zuma Game", u: "zuma-game", d: "HARD", c: "backtracking" },
  { t: "Partition to K Equal Sum Subsets", u: "partition-to-k-equal-sum-subsets", d: "MEDIUM", c: "backtracking" },
  { t: "Flip Game II", u: "flip-game-ii", d: "MEDIUM", c: "backtracking" },
  { t: "Additive Number", u: "additive-number", d: "MEDIUM", c: "backtracking" },

  // ─── GRAPH (366-420) ──────────────────────────────────────────────────────
  { t: "Find the Town Judge", u: "find-the-town-judge", d: "EASY", c: "graph" },
  { t: "Find Center of Star Graph", u: "find-center-of-star-graph", d: "EASY", c: "graph" },
  { t: "Number of Provinces", u: "number-of-provinces", d: "MEDIUM", c: "graph" },
  { t: "Graph Valid Tree", u: "graph-valid-tree", d: "MEDIUM", c: "graph" },
  { t: "Number of Connected Components in an Undirected Graph", u: "number-of-connected-components-in-an-undirected-graph", d: "MEDIUM", c: "graph" },
  { t: "Course Schedule", u: "course-schedule", d: "MEDIUM", c: "graph" },
  { t: "Course Schedule II", u: "course-schedule-ii", d: "MEDIUM", c: "graph" },
  { t: "Redundant Connection", u: "redundant-connection", d: "MEDIUM", c: "graph" },
  { t: "Accounts Merge", u: "accounts-merge", d: "MEDIUM", c: "graph" },
  { t: "Smallest String With Swaps", u: "smallest-string-with-swaps", d: "MEDIUM", c: "graph" },
  { t: "Network Delay Time", u: "network-delay-time", d: "MEDIUM", c: "graph" },
  { t: "Path With Minimum Effort", u: "path-with-minimum-effort", d: "MEDIUM", c: "graph" },
  { t: "Cheapest Flights Within K Stops", u: "cheapest-flights-within-k-stops", d: "MEDIUM", c: "graph" },
  { t: "Find Eventual Safe States", u: "find-eventual-safe-states", d: "MEDIUM", c: "graph" },
  { t: "Is Graph Bipartite?", u: "is-graph-bipartite", d: "MEDIUM", c: "graph" },
  { t: "Minimum Number of Vertices to Reach All Nodes", u: "minimum-number-of-vertices-to-reach-all-nodes", d: "MEDIUM", c: "graph" },
  { t: "All Paths From Source Lead to Destination", u: "all-paths-from-source-lead-to-destination", d: "MEDIUM", c: "graph" },
  { t: "Keys and Rooms", u: "keys-and-rooms", d: "MEDIUM", c: "graph" },
  { t: "Number of Operations to Make Network Connected", u: "number-of-operations-to-make-network-connected", d: "MEDIUM", c: "graph" },
  { t: "Reconstruct Itinerary", u: "reconstruct-itinerary", d: "HARD", c: "graph" },
  { t: "Maximum Number of Points with Cost", u: "maximum-number-of-points-with-cost", d: "MEDIUM", c: "graph" },
  { t: "Swim in Rising Water", u: "swim-in-rising-water", d: "HARD", c: "graph" },
  { t: "Minimum Cost to Reach Destination in Time", u: "minimum-cost-to-reach-destination-in-time", d: "HARD", c: "graph" },
  { t: "Maximum Employees to Be Invited to a Meeting", u: "maximum-employees-to-be-invited-to-a-meeting", d: "HARD", c: "graph" },
  { t: "Longest Increasing Path in a Matrix", u: "longest-increasing-path-in-a-matrix", d: "HARD", c: "graph" },
  { t: "Alien Dictionary", u: "alien-dictionary", d: "HARD", c: "graph" },
  { t: "Sequence Reconstruction", u: "sequence-reconstruction", d: "MEDIUM", c: "graph" },
  { t: "Parallel Courses", u: "parallel-courses", d: "MEDIUM", c: "graph" },
  { t: "Sort Items by Groups Respecting Dependencies", u: "sort-items-by-groups-respecting-dependencies", d: "HARD", c: "graph" },
  { t: "Critical Connections in a Network", u: "critical-connections-in-a-network", d: "HARD", c: "graph" },
  { t: "Find Critical and Pseudo-Critical Edges in MST", u: "find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree", d: "HARD", c: "graph" },
  { t: "Connecting Cities With Minimum Cost", u: "connecting-cities-with-minimum-cost", d: "MEDIUM", c: "graph" },
  { t: "Optimize Water Distribution in a Village", u: "optimize-water-distribution-in-a-village", d: "HARD", c: "graph" },
  { t: "Remove Max Number of Edges to Keep Graph Fully Traversable", u: "remove-max-number-of-edges-to-keep-graph-fully-traversable", d: "HARD", c: "graph" },
  { t: "Reorder Routes to Make All Paths Lead to City Zero", u: "reorder-routes-to-make-all-paths-lead-to-the-city-zero", d: "MEDIUM", c: "graph" },
  { t: "Second Minimum Time to Reach Destination", u: "second-minimum-time-to-reach-destination", d: "HARD", c: "graph" },
  { t: "Shortest Path Visiting All Nodes", u: "shortest-path-visiting-all-nodes", d: "HARD", c: "graph" },
  { t: "Minimum Height Trees", u: "minimum-height-trees", d: "MEDIUM", c: "graph" },
  { t: "Evaluate Division", u: "evaluate-division", d: "MEDIUM", c: "graph" },
  { t: "Count Unreachable Pairs of Nodes in an Undirected Graph", u: "count-unreachable-pairs-of-nodes-in-an-undirected-graph", d: "MEDIUM", c: "graph" },
  { t: "Detonate the Maximum Bombs", u: "detonate-the-maximum-bombs", d: "MEDIUM", c: "graph" },
  { t: "Minimum Fuel Cost to Report to the Capital", u: "minimum-fuel-cost-to-report-to-the-capital", d: "MEDIUM", c: "graph" },
  { t: "Loud and Rich", u: "loud-and-rich", d: "MEDIUM", c: "graph" },
  { t: "Possible Bipartition", u: "possible-bipartition", d: "MEDIUM", c: "graph" },
  { t: "Making a Large Island", u: "making-a-large-island", d: "HARD", c: "graph" },
  { t: "Similar String Groups", u: "similar-string-groups", d: "HARD", c: "graph" },
  { t: "Number of Islands II", u: "number-of-islands-ii", d: "HARD", c: "graph" },
  { t: "Satisfiability of Equality Equations", u: "satisfiability-of-equality-equations", d: "MEDIUM", c: "graph" },
  { t: "Find if Path Exists in Graph", u: "find-if-path-exists-in-graph", d: "EASY", c: "graph" },
  { t: "Number of Closed Islands", u: "number-of-closed-islands", d: "MEDIUM", c: "graph" },
  { t: "The Earliest Moment When Everyone Become Friends", u: "the-earliest-moment-when-everyone-become-friends", d: "MEDIUM", c: "graph" },
  { t: "Shortest Bridge", u: "shortest-bridge", d: "MEDIUM", c: "graph" },
  { t: "Number of Enclaves", u: "number-of-enclaves", d: "MEDIUM", c: "graph" },
  { t: "Count Sub Islands", u: "count-sub-islands", d: "MEDIUM", c: "graph" },

  // ─── DYNAMIC PROGRAMMING (421-500) ────────────────────────────────────────
  { t: "Climbing Stairs (DP)", u: "climbing-stairs", d: "EASY", c: "dynamic programming" },
  { t: "House Robber", u: "house-robber", d: "MEDIUM", c: "dynamic programming" },
  { t: "House Robber II", u: "house-robber-ii", d: "MEDIUM", c: "dynamic programming" },
  { t: "Coin Change", u: "coin-change", d: "MEDIUM", c: "dynamic programming" },
  { t: "Longest Increasing Subsequence", u: "longest-increasing-subsequence", d: "MEDIUM", c: "dynamic programming" },
  { t: "Longest Common Subsequence", u: "longest-common-subsequence", d: "MEDIUM", c: "dynamic programming" },
  { t: "Word Break (DP)", u: "word-break", d: "MEDIUM", c: "dynamic programming" },
  { t: "Unique Paths", u: "unique-paths", d: "MEDIUM", c: "dynamic programming" },
  { t: "Unique Paths II", u: "unique-paths-ii", d: "MEDIUM", c: "dynamic programming" },
  { t: "Minimum Path Sum", u: "minimum-path-sum", d: "MEDIUM", c: "dynamic programming" },
  { t: "Triangle", u: "triangle", d: "MEDIUM", c: "dynamic programming" },
  { t: "Maximum Sum Circular Subarray", u: "maximum-sum-circular-subarray", d: "MEDIUM", c: "dynamic programming" },
  { t: "Jump Game (DP)", u: "jump-game", d: "MEDIUM", c: "dynamic programming" },
  { t: "Jump Game VI", u: "jump-game-vi", d: "MEDIUM", c: "dynamic programming" },
  { t: "Jump Game VII", u: "jump-game-vii", d: "MEDIUM", c: "dynamic programming" },
  { t: "Decode Ways (DP)", u: "decode-ways", d: "MEDIUM", c: "dynamic programming" },
  { t: "Partition Equal Subset Sum", u: "partition-equal-subset-sum", d: "MEDIUM", c: "dynamic programming" },
  { t: "Target Sum", u: "target-sum", d: "MEDIUM", c: "dynamic programming" },
  { t: "Last Stone Weight II", u: "last-stone-weight-ii", d: "MEDIUM", c: "dynamic programming" },
  { t: "Coin Change II", u: "coin-change-ii", d: "MEDIUM", c: "dynamic programming" },
  { t: "Perfect Squares", u: "perfect-squares", d: "MEDIUM", c: "dynamic programming" },
  { t: "Minimum Cost For Tickets", u: "minimum-cost-for-tickets", d: "MEDIUM", c: "dynamic programming" },
  { t: "Counting Bits", u: "counting-bits", d: "EASY", c: "dynamic programming" },
  { t: "Range Sum Query - Immutable", u: "range-sum-query-immutable", d: "EASY", c: "dynamic programming" },
  { t: "Longest Arithmetic Subsequence", u: "longest-arithmetic-subsequence", d: "MEDIUM", c: "dynamic programming" },
  { t: "Longest Arithmetic Subsequence of Given Difference", u: "longest-arithmetic-subsequence-of-given-difference", d: "MEDIUM", c: "dynamic programming" },
  { t: "Number of Longest Increasing Subsequence", u: "number-of-longest-increasing-subsequence", d: "MEDIUM", c: "dynamic programming" },
  { t: "Russian Doll Envelopes", u: "russian-doll-envelopes", d: "HARD", c: "dynamic programming" },
  { t: "Knapsack Problem (0/1)", u: "partition-equal-subset-sum", d: "MEDIUM", c: "dynamic programming" },
  { t: "Edit Distance", u: "edit-distance", d: "MEDIUM", c: "dynamic programming" },
  { t: "Interleaving String", u: "interleaving-string", d: "MEDIUM", c: "dynamic programming" },
  { t: "Wildcard Matching (DP)", u: "wildcard-matching", d: "HARD", c: "dynamic programming" },
  { t: "Regular Expression Matching (DP)", u: "regular-expression-matching", d: "HARD", c: "dynamic programming" },
  { t: "Palindrome Partitioning II", u: "palindrome-partitioning-ii", d: "HARD", c: "dynamic programming" },
  { t: "Distinct Subsequences (DP)", u: "distinct-subsequences", d: "HARD", c: "dynamic programming" },
  { t: "Scramble String (DP)", u: "scramble-string", d: "HARD", c: "dynamic programming" },
  { t: "Maximum Rectangle (DP)", u: "maximal-rectangle", d: "HARD", c: "dynamic programming" },
  { t: "Longest Palindromic Subsequence", u: "longest-palindromic-subsequence", d: "MEDIUM", c: "dynamic programming" },
  { t: "Stone Game", u: "stone-game", d: "MEDIUM", c: "dynamic programming" },
  { t: "Stone Game II", u: "stone-game-ii", d: "MEDIUM", c: "dynamic programming" },
  { t: "Stone Game VII", u: "stone-game-vii", d: "MEDIUM", c: "dynamic programming" },
  { t: "Burst Balloons", u: "burst-balloons", d: "HARD", c: "dynamic programming" },
  { t: "Strange Printer", u: "strange-printer", d: "HARD", c: "dynamic programming" },
  { t: "Remove Boxes", u: "remove-boxes", d: "HARD", c: "dynamic programming" },
  { t: "Minimum Cost to Merge Stones", u: "minimum-cost-to-merge-stones", d: "HARD", c: "dynamic programming" },
  { t: "Zuma Game (DP)", u: "zuma-game", d: "HARD", c: "dynamic programming" },
  { t: "Largest Divisible Subset", u: "largest-divisible-subset", d: "MEDIUM", c: "dynamic programming" },
  { t: "Arithmetic Slices", u: "arithmetic-slices", d: "MEDIUM", c: "dynamic programming" },
  { t: "Arithmetic Slices II - Subsequence", u: "arithmetic-slices-ii-subsequence", d: "HARD", c: "dynamic programming" },
  { t: "Fibonacci Number (DP)", u: "fibonacci-number", d: "EASY", c: "dynamic programming" },
  { t: "N-th Tribonacci Number", u: "n-th-tribonacci-number", d: "EASY", c: "dynamic programming" },
  { t: "Minimum Falling Path Sum", u: "minimum-falling-path-sum", d: "MEDIUM", c: "dynamic programming" },
  { t: "Maximal Square", u: "maximal-square", d: "MEDIUM", c: "dynamic programming" },
  { t: "Maximum Product Subarray (DP)", u: "maximum-product-subarray", d: "MEDIUM", c: "dynamic programming" },
  { t: "Delete and Earn", u: "delete-and-earn", d: "MEDIUM", c: "dynamic programming" },
  { t: "Domino and Tromino Tiling", u: "domino-and-tromino-tiling", d: "MEDIUM", c: "dynamic programming" },
  { t: "Minimum Path Cost in a Grid", u: "minimum-path-cost-in-a-grid", d: "MEDIUM", c: "dynamic programming" },
  { t: "Out of Boundary Paths", u: "out-of-boundary-paths", d: "MEDIUM", c: "dynamic programming" },
  { t: "Knight Probability in Chessboard", u: "knight-probability-in-chessboard", d: "MEDIUM", c: "dynamic programming" },
  { t: "Profitable Schemes", u: "profitable-schemes", d: "HARD", c: "dynamic programming" },
  { t: "Number of Dice Rolls With Target Sum", u: "number-of-dice-rolls-with-target-sum", d: "MEDIUM", c: "dynamic programming" },
  { t: "Dice Roll Simulation", u: "dice-roll-simulation", d: "HARD", c: "dynamic programming" },
  { t: "Tallest Billboard", u: "tallest-billboard", d: "HARD", c: "dynamic programming" },
  { t: "Best Time to Buy and Sell Stock with Cooldown", u: "best-time-to-buy-and-sell-stock-with-cooldown", d: "MEDIUM", c: "dynamic programming" },
  { t: "Best Time to Buy and Sell Stock with Transaction Fee", u: "best-time-to-buy-and-sell-stock-with-transaction-fee", d: "MEDIUM", c: "dynamic programming" },
  { t: "Paint House", u: "paint-house", d: "MEDIUM", c: "dynamic programming" },
  { t: "Paint House II", u: "paint-house-ii", d: "HARD", c: "dynamic programming" },
  { t: "Count Vowels Permutation", u: "count-vowels-permutation", d: "HARD", c: "dynamic programming" },
  { t: "Minimum Number of Removals to Make Mountain Array", u: "minimum-number-of-removals-to-make-mountain-array", d: "HARD", c: "dynamic programming" },
  { t: "Maximum Profit in Job Scheduling", u: "maximum-profit-in-job-scheduling", d: "HARD", c: "dynamic programming" },
  { t: "Number of Ways to Form a Target String Given a Dictionary", u: "number-of-ways-to-form-a-target-string-given-a-dictionary", d: "HARD", c: "dynamic programming" },
  { t: "Maximum Score from Performing Multiplication Operations", u: "maximum-score-from-performing-multiplication-operations", d: "HARD", c: "dynamic programming" },
  { t: "Count Different Palindromic Subsequences", u: "count-different-palindromic-subsequences", d: "HARD", c: "dynamic programming" },
  { t: "Cherry Pickup", u: "cherry-pickup", d: "HARD", c: "dynamic programming" },
  { t: "Cherry Pickup II", u: "cherry-pickup-ii", d: "HARD", c: "dynamic programming" },
  { t: "Minimum Difficulty of a Job Schedule", u: "minimum-difficulty-of-a-job-schedule", d: "HARD", c: "dynamic programming" },
];

// Deduplicate by URL (some problems appear in multiple topic sections)
function dedup(problems: Problem[]): Problem[] {
  const seen = new Set<string>();
  return problems.filter(({ u }) => {
    if (seen.has(u)) return false;
    seen.add(u);
    return true;
  });
}

async function main() {
  // Seed preset tags
  for (const name of PRESET_TAGS) {
    await db.tag.upsert({
      where: { name },
      update: { isPreset: true },
      create: { name, isPreset: true },
    });
  }
  console.log(`Seeded ${PRESET_TAGS.length} preset tags.`);

  // Seed sheet problems (idempotent — skips existing by URL)
  const unique = dedup(PROBLEMS);
  let inserted = 0;
  for (let i = 0; i < unique.length; i++) {
    const { t: title, u: slug, d: difficulty, c: topic } = unique[i];
    await db.sheetProblem.upsert({
      where: { url: `${BASE}${slug}/` },
      update: {},
      create: {
        title,
        url: `${BASE}${slug}/`,
        difficulty,
        topic,
        order: i + 1,
      },
    });
    inserted++;
  }
  console.log(`Seeded ${inserted} sheet problems.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
